nelmio_api_doc:
    documentation:
        info:
            title: New Living
            description: Official New Living API documentation
            version: 1.0.0
        paths:
            /example:
                post:
                    summary: Example enpoint
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                            format: email
                    responses:
                        '200':
                            description: Success
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            message:
                                                type: string

    areas:
        path_patterns:
            - ^/api(?!/doc$)
