version: "3.9"

services:
  new-living-dev:
    ports:
      - "80:80"
    volumes:
      - .:/var/www/new-living/
    networks:
      - messaging
      - database-connection

  new-living-database:
    environment:
      POSTGRES_DB: new-living-db
      POSTGRES_PASSWORD: new-living
      POSTGRES_USER: new-living
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "new-living", "-d", "new-living-db" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - database-volume:/var/lib/postgresql/data:rw
    networks:
      - database-connection

  new-living-mailer:
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:1080" ]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "1025"
      - "1080"

  new-living-rabbitmq:
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - messaging

volumes:
  database-volume:
  rabbitmq-data:

networks:
  messaging:
  database-connection: