version: "3.9"

services:
  new-living-dev:
    ports:
      - "80:80"
    volumes:
      - .:/var/www/new-living/
    networks:
      - default

  new-living-database:
    environment:
      POSTGRES_DB: new-living-db
      POSTGRES_PASSWORD: new-living
      POSTGRES_USER: new-living
    ports:
      - "5432:5432"
    volumes:
      - new-living-db-volume:/var/lib/postgresql/data:rw

  new-living-mailer:
    ports:
      - "1025"
      - "1080"
  rabbitmq:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  new-living-db-volume:
  rabbitmq-data:
  rabbitmq-log:

networks:
  default: