version: "3.9"

services:
  new-living-base:
    container_name: new-living-base
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    image: new-living-base

  new-living-dev:
    container_name: new-living-dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: new-living-dev
    depends_on:
      new-living-database:
        condition: service_healthy
      new-living-rabbitmq:
        condition: service_healthy
      new-living-mailer:
        condition: service_healthy

  new-living-database:
    container_name: new-living-database
    image: postgres:14.3-alpine

  new-living-mailer:
    container_name: new-living-mailcatcher
    image: schickling/mailcatcher

  new-living-rabbitmq:
    container_name: new-living-rabbitmq
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    image: new-living-rabbitmq
