version: "3.9"

networks:
  default:

services:

  new-living-api-base:
    container_name: new-living-api-base
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    image: new-living-api-base

  new-living-api-dev:
    container_name: new-living-api-dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8080:80"
    image: new-living-api-dev
    volumes:
      - .:/var/www/new-living-api/
    networks:
      - default

  new-living-api-database:
    image: postgres:14.3-alpine
    container_name: new-living-api-database
    environment:
      POSTGRES_DB: new-living-api-db
      POSTGRES_PASSWORD: new-living-api
      POSTGRES_USER: new-living-api
    volumes:
      - new-living-api-db-volume:/var/lib/postgresql/data:rw


volumes:
  new-living-api-db-volume:
