parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Core\Domain\Clock:
    class: App\Core\Domain\Clock\TestClock
    public: true

  App\Core\Application\Query\UserQuery:
    class: App\Core\Infrastructure\Doctrine\Query\DBALUserQuery
    public: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'